/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import javax.swing.JOptionPane;

/**
 * @author Lucas Sala Alves
 */
public class Tela_Espaco_cor extends javax.swing.JFrame {
    public Tela_Principal_ telaPrincipal;
    public static boolean lote;
    public int    Deteccao_tipo = 0;

    public Tela_Espaco_cor(Tela_Principal_ parent, boolean lote) {
        this.telaPrincipal = parent;
        this.lote = lote;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Confirmar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        YCbCr = new javax.swing.JCheckBox();
        XYZ = new javax.swing.JCheckBox();
        Ambos = new javax.swing.JCheckBox();
        Y = new javax.swing.JCheckBox();
        Cb = new javax.swing.JCheckBox();
        Cr = new javax.swing.JCheckBox();
        X = new javax.swing.JCheckBox();
        Yxyz = new javax.swing.JCheckBox();
        Z = new javax.swing.JCheckBox();
        Ymin = new javax.swing.JSpinner();
        Ymax = new javax.swing.JSpinner();
        Cbmin = new javax.swing.JSpinner();
        Cbmax = new javax.swing.JSpinner();
        Crmin = new javax.swing.JSpinner();
        Crmax = new javax.swing.JSpinner();
        Xmin = new javax.swing.JSpinner();
        Xmax = new javax.swing.JSpinner();
        Yxyzmin = new javax.swing.JSpinner();
        Yxyzmax = new javax.swing.JSpinner();
        Zmin = new javax.swing.JSpinner();
        Zmax = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Interface de detecção de pele");
        setIconImages(null);
        setResizable(false);

        Confirmar.setText("OK");
        Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setToolTipText("");
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setName(""); // NOI18N

        YCbCr.setForeground(new java.awt.Color(0, 0, 204));
        YCbCr.setSelected(true);
        YCbCr.setText("YCbCr");
        YCbCr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YCbCrActionPerformed(evt);
            }
        });

        XYZ.setForeground(new java.awt.Color(204, 0, 0));
        XYZ.setText("XYZ");
        XYZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XYZActionPerformed(evt);
            }
        });

        Ambos.setText("Ambos");
        Ambos.setToolTipText("");
        Ambos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmbosActionPerformed(evt);
            }
        });

        Y.setForeground(new java.awt.Color(0, 0, 204));
        Y.setSelected(true);
        Y.setText("Y");
        Y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YActionPerformed(evt);
            }
        });

        Cb.setForeground(new java.awt.Color(0, 0, 204));
        Cb.setSelected(true);
        Cb.setText("Cb");
        Cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbActionPerformed(evt);
            }
        });

        Cr.setForeground(new java.awt.Color(0, 0, 204));
        Cr.setSelected(true);
        Cr.setText("Cr");
        Cr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrActionPerformed(evt);
            }
        });

        X.setForeground(new java.awt.Color(204, 0, 0));
        X.setText("X");
        X.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XActionPerformed(evt);
            }
        });

        Yxyz.setForeground(new java.awt.Color(204, 0, 0));
        Yxyz.setText("Y");
        Yxyz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YxyzActionPerformed(evt);
            }
        });

        Z.setForeground(new java.awt.Color(204, 0, 0));
        Z.setText("Z");
        Z.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZActionPerformed(evt);
            }
        });

        Ymin.setModel(new javax.swing.SpinnerNumberModel(85, 0, 255, 1));

        Ymax.setModel(new javax.swing.SpinnerNumberModel(135, 0, 255, 1));
        Ymax.setToolTipText("");

        Cbmin.setModel(new javax.swing.SpinnerNumberModel(80, 0, 255, 1));

        Cbmax.setModel(new javax.swing.SpinnerNumberModel(180, 0, 255, 1));

        Crmin.setModel(new javax.swing.SpinnerNumberModel(135, 0, 255, 1));

        Crmax.setModel(new javax.swing.SpinnerNumberModel(255, 0, 255, 1));

        Xmin.setModel(new javax.swing.SpinnerNumberModel(120, 0, 255, 1));
        Xmin.setEnabled(false);

        Xmax.setModel(new javax.swing.SpinnerNumberModel(225, 0, 255, 1));
        Xmax.setEnabled(false);

        Yxyzmin.setModel(new javax.swing.SpinnerNumberModel(67, 0, 255, 1));
        Yxyzmin.setEnabled(false);

        Yxyzmax.setModel(new javax.swing.SpinnerNumberModel(220, 0, 255, 1));
        Yxyzmax.setEnabled(false);

        Zmin.setModel(new javax.swing.SpinnerNumberModel(0, 0, 255, 1));
        Zmin.setEnabled(false);

        Zmax.setModel(new javax.swing.SpinnerNumberModel(278, 0, 278, 1));
        Zmax.setEnabled(false);

        jLabel1.setText("Mín");

        jLabel2.setText("Máx");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(YCbCr)
                                    .addComponent(XYZ))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Y)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(X)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addComponent(Yxyz)))
                                    .addComponent(Cb)
                                    .addComponent(Cr)))
                            .addComponent(Ambos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Z)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Ymin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Cbmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(Crmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cbmax, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ymax, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Crmax, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(20, 20, 20))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Zmin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Yxyzmin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Xmin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Xmax, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Yxyzmax, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Zmax, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ymin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ymax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Y, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cbmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cbmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cb)
                            .addComponent(YCbCr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Crmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Crmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cr))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Xmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Xmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(X))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Ambos)
                                .addGap(33, 33, 33)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Yxyzmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Yxyzmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Yxyz)
                                .addComponent(XYZ)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Zmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Zmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Z))
                .addContainerGap())
        );

        Ymin.getAccessibleContext().setAccessibleName("");
        Ymin.getAccessibleContext().setAccessibleDescription("");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Seleção do espaço de cor e das faixas de valores ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Confirmar)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Confirmar)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarActionPerformed
        javax.swing.JDialog F = new javax.swing.JDialog();
        
        if(Y.isSelected() || Cb.isSelected()   || Cr.isSelected() || 
           X.isSelected() || Yxyz.isSelected() || Z.isSelected()){
            
            if(Y.isSelected() || Cb.isSelected()   || Cr.isSelected())
                Deteccao_tipo += 1;
            if(X.isSelected() || Yxyz.isSelected() || Z.isSelected())
                Deteccao_tipo -= 1;
            
            if(!lote)
                telaPrincipal.Aplicar_SkinDetection_Imagem(this);
            else
                telaPrincipal.Aplicar_SkinDetection_Lote(this);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(F, "Nenhuma opção foi selecionada!");
        }
    }//GEN-LAST:event_ConfirmarActionPerformed

    private void YCbCrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YCbCrActionPerformed
        Ymin.setEnabled(YCbCr.isSelected());
        Ymax.setEnabled(YCbCr.isSelected());
        Cbmin.setEnabled(YCbCr.isSelected());
        Cbmax.setEnabled(YCbCr.isSelected());
        Crmin.setEnabled(YCbCr.isSelected());
        Crmax.setEnabled(YCbCr.isSelected());
        
        Y.setSelected(YCbCr.isSelected());
        Cb.setSelected(YCbCr.isSelected());
        Cr.setSelected(YCbCr.isSelected());
        
        if(XYZ.isSelected()){
            Ambos.setSelected(YCbCr.isSelected());
        }
    }//GEN-LAST:event_YCbCrActionPerformed

    private void YActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YActionPerformed
        Ymin.setEnabled(Y.isSelected());
        Ymax.setEnabled(Y.isSelected());
        if(Cb.isSelected() && Cr.isSelected()){
            YCbCr.setSelected(Y.isSelected());
            if(XYZ.isSelected())
                Ambos.setSelected(Y.isSelected());
        }
    }//GEN-LAST:event_YActionPerformed

    private void CbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbActionPerformed
        Cbmin.setEnabled(Cb.isSelected());
        Cbmax.setEnabled(Cb.isSelected());
        if(Y.isSelected() && Cr.isSelected()){
            YCbCr.setSelected(Cb.isSelected());
            if(XYZ.isSelected())
                Ambos.setSelected(Cb.isSelected());
        }
    }//GEN-LAST:event_CbActionPerformed

    private void CrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrActionPerformed
        Crmin.setEnabled(Cr.isSelected());
        Crmax.setEnabled(Cr.isSelected());
        if(Y.isSelected() && Cb.isSelected()){
            YCbCr.setSelected(Cr.isSelected());
            if(XYZ.isSelected())
                Ambos.setSelected(Cr.isSelected());
        }
    }//GEN-LAST:event_CrActionPerformed

    private void XYZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XYZActionPerformed
        X.setSelected(XYZ.isSelected());
        Yxyz.setSelected(XYZ.isSelected());
        Z.setSelected(XYZ.isSelected());
        Xmin.setEnabled(XYZ.isSelected());
        Xmax.setEnabled(XYZ.isSelected());
        Yxyzmin.setEnabled(XYZ.isSelected());
        Yxyzmax.setEnabled(XYZ.isSelected());
        Zmin.setEnabled(XYZ.isSelected());
        Zmax.setEnabled(XYZ.isSelected());
        
        if(YCbCr.isSelected()){
            Ambos.setSelected(XYZ.isSelected());
        }
    }//GEN-LAST:event_XYZActionPerformed
    
    private void XActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XActionPerformed
        Xmin.setEnabled(X.isSelected());
        Xmax.setEnabled(X.isSelected());
        if(Yxyz.isSelected() && Z.isSelected()){
            XYZ.setSelected(X.isSelected());
            if(YCbCr.isSelected())
                Ambos.setSelected(X.isSelected());
        }
    }//GEN-LAST:event_XActionPerformed

    private void YxyzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YxyzActionPerformed
        Yxyzmin.setEnabled(Yxyz.isSelected());
        Yxyzmax.setEnabled(Yxyz.isSelected());
        if(X.isSelected() && Z.isSelected()){
            XYZ.setSelected(Yxyz.isSelected());
            if(YCbCr.isSelected())
                Ambos.setSelected(Yxyz.isSelected());
        }
    }//GEN-LAST:event_YxyzActionPerformed

    private void ZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZActionPerformed
        Zmin.setEnabled(Z.isSelected());
        Zmax.setEnabled(Z.isSelected());
        if(Yxyz.isSelected() && X.isSelected()){
            XYZ.setSelected(Z.isSelected());
            if(YCbCr.isSelected())
                Ambos.setSelected(Z.isSelected());
        }
    }//GEN-LAST:event_ZActionPerformed

    private void AmbosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmbosActionPerformed
        YCbCr.setSelected(Ambos.isSelected());
        XYZ.setSelected(Ambos.isSelected());
        Y.setSelected(Ambos.isSelected());
        Cb.setSelected(Ambos.isSelected());
        Cr.setSelected(Ambos.isSelected());
        X.setSelected(Ambos.isSelected());
        Yxyz.setSelected(Ambos.isSelected());
        Z.setSelected(Ambos.isSelected());
        Ymin.setEnabled(Ambos.isSelected());
        Ymax.setEnabled(Ambos.isSelected());
        Cbmin.setEnabled(Ambos.isSelected());
        Cbmax.setEnabled(Ambos.isSelected());
        Crmin.setEnabled(Ambos.isSelected());
        Crmax.setEnabled(Ambos.isSelected());
        Xmin.setEnabled(Ambos.isSelected());
        Xmax.setEnabled(Ambos.isSelected());
        Yxyzmin.setEnabled(Ambos.isSelected());
        Yxyzmax.setEnabled(Ambos.isSelected());
        Zmin.setEnabled(Ambos.isSelected());
        Zmax.setEnabled(Ambos.isSelected());
    }//GEN-LAST:event_AmbosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Espaco_cor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            Tela_Espaco_cor dialog = new Tela_Espaco_cor(null,lote);
            dialog.setLocationRelativeTo(null);
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Ambos;
    private javax.swing.JCheckBox Cb;
    public javax.swing.JSpinner Cbmax;
    public javax.swing.JSpinner Cbmin;
    private javax.swing.JButton Confirmar;
    private javax.swing.JCheckBox Cr;
    public javax.swing.JSpinner Crmax;
    public javax.swing.JSpinner Crmin;
    private javax.swing.JCheckBox X;
    private javax.swing.JCheckBox XYZ;
    public javax.swing.JSpinner Xmax;
    public javax.swing.JSpinner Xmin;
    private javax.swing.JCheckBox Y;
    private javax.swing.JCheckBox YCbCr;
    public javax.swing.JSpinner Ymax;
    public javax.swing.JSpinner Ymin;
    private javax.swing.JCheckBox Yxyz;
    public javax.swing.JSpinner Yxyzmax;
    public javax.swing.JSpinner Yxyzmin;
    private javax.swing.JCheckBox Z;
    public javax.swing.JSpinner Zmax;
    public javax.swing.JSpinner Zmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
